Check for PublicKey is valid.
p2p-org/solana-swift pull request #72
Opened 2023-03-31 06:30 UTC by TheHmmka

Just one more property to check if the PublicKey is valid or not.

2023-03-31 07:17 UTC, bigearsenal requested changes
Hi there, thank you for your contribution, just please re-add the extension in Package.swift. Thank you

2023-04-19 13:09 UTC, TheHmmka commented
Done!

2023-04-20 03:38 UTC, bigearsenal requested changes

2023-04-20 03:38 UTC, bigearsenal commented on Package.swift
> +        .package(name: "secp256k1", url: "https://github.com/v57/secp256k1.c.git", from: "0.1.0"),
Hello. We can not verify this package right now, and the change is not related to the PR. Please reverse it.
The package secp256k1 will be verified in another PR

2023-04-20 03:38 UTC, bigearsenal commented on SolanaSwift.podspec
> +  s.dependency 'secp256k1.c', '~> 0.1.0'
The same for this.

2024-03-19 11:57 UTC, closed without merging